language: node_js

node_js:
  - "node"
  - "6"
  - "5"
  - "4"

sudo: false

script:
  - echo "module.exports = { consumer_key: '', consumer_secret: '', access_token: '', access_token_secret: '' };" > config.js
  - npm test

notifications:
  email: false

after_success:
  - npm run coveralls

